In [12]:
import numpy as np

# Create a  matrix
m1 = np.array([[1, 2],[3, 4]])
m2=np.array([[4,3],[3,9]])
print("Matrix 1:")
print(m1)

print("Matrix 2:")
print(m2)
print("Addition of matrix :\n",m1+m2)

print("Subtraction  of matrix :\n",m1-m2)

print("Multiplication of matrix :\n",m1*m2)


print("Division of matrix :\n",m1/m2)

print("Dot Product of matrix :\n",np.dot(m1,m2.T))

print("Matrix transpose :\n",m1.T)

Matrix 1:
[[1 2]
 [3 4]]
Matrix 2:
[[4 3]
 [3 9]]
Addition of matrix :
 [[ 5  5]
 [ 6 13]]
Subtraction  of matrix :
 [[-3 -1]
 [ 0 -5]]
Multiplication of matrix :
 [[ 4  6]
 [ 9 36]]
Division of matrix :
 [[0.25       0.66666667]
 [1.         0.44444444]]
Dot Product of matrix :
 [[10 21]
 [24 45]]
Matrix transpose :
 [[1 3]
 [2 4]]
